### ISSUE TITLE
Getting 'Assignment to constant variable' when running in node for Inertia SSR

### ISSUE THREAD

**Issue by iamroi** [vueform/multiselect#200]
### Version

* Vue version: 3

### Description

**Template:**

```           
             <Multiselect
                mode="multiple"
                :options="[
                    {
                        label: 'Foo',
                        options: [
                            {label: 'Bar', value: 'bar'}
                        ]
                    },
                ]"
                v-model="foobar"
                :groups="true"
            >
            </Multiselect>
```

I'm using Inertia and this works fine on the browser side. But when I try to run the code for SSR like `node -r esm ./public/js/ssr.js`, I'm getting the below error

```
[Vue warn]: Unhandled error during execution of render function
  at <Multiselect mode="multiple" options= [ { label: 'Foo', options: [ [Object] ] } ] valueProp="value"  ... >
C:\Workspace\web.carbar\node_modules\@vueform\multiselect\dist\multiselect.js:48
TypeError: Assignment to constant variable.
    at D (C:\Workspace\web.carbar\node_modules\@vueform\multiselect\dist\multiselect.js:48:49)
    at C:\Workspace\web.carbar\node_modules\@vueform\multiselect\dist\multiselect.js:94:26
    at Proxy.map (<anonymous>)
    at ReactiveEffect.fn (C:\Workspace\web.carbar\node_modules\@vueform\multiselect\dist\multiselect.js:92:49)
    at ReactiveEffect.run (C:\Workspace\web.carbar\node_modules\@vue\reactivity\dist\reactivity.cjs.js:151:25)
    at ComputedRefImpl.get value [as value] (C:\Workspace\web.carbar\node_modules\@vue\reactivity\dist\reactivity.cjs.js:1092:39)
    at unref (C:\Workspace\web.carbar\node_modules\@vue\reactivity\dist\reactivity.cjs.js:1000:29)
    at Object.get (C:\Workspace\web.carbar\node_modules\@vue\reactivity\dist\reactivity.cjs.js:1003:37)
    at Object.get (C:\Workspace\web.carbar\node_modules\@vue\runtime-core\dist\runtime-core.cjs.js:6618:34)
    at Proxy._bf9‍.r.P.render (C:\Workspace\web.carbar\node_modules\@vueform\multiselect\dist\multiselect.js:918:130)
```

Just to understand the issue, I went into the file @vueform/multiselect/dist/multiselect.js(pretty formatted) to play around and the below change fixed the issue. Hope this will be helpful to identify why it's throwing the above error

![image](https://user-images.githubusercontent.com/4452859/154020837-07594546-3b0a-414f-9512-57fa5a5fd86a.png)

**Comment by adamberecz** [comment]
Feel free to reopen with a reproducible repo.
